### ISSUE TITLE
CMS picker for "link to" has left-hand side hidden

### ISSUE THREAD

**Issue by koalie** [w3c/w3c-website#746]
**Describe the issue**
The pop-in that appears when clicking "Link to [an entry, a category, an asset]" does not display fully the left-hand side. The only way to know which section is selected is by looking at the grey label at the bottom left. See screenshots.

<img width="763" height="222" alt="Image" src="https://github.com/user-attachments/assets/dc53cb1b-324b-4c57-83ac-72d3fc7e05b9" />

<img width="897" height="646" alt="Image" src="https://github.com/user-attachments/assets/e0bed21b-b29b-4a35-97b9-866b1a6e0007" />

**Additional context**
Again, this only happens in a both private and non-private window in Firefox 140.0.4 (on Mac OS 15.5), but not in Safari.
Note that I can widen or enlarge the size of the picker, but the left-hand side stays fixed.

**Comment by JamieC24** [comment]
Hi @koalie,

Can you check this again? I've just had a look on my development environment and this is what I see when I go to link an entry (This was on Firefox) :

<img width="1284" height="606" alt="Image" src="https://github.com/user-attachments/assets/ba488ed8-38b1-4dae-808a-5088f693498e" />

This may have been something that was addressed by Craft in the intervening time between now and this ticket being raised

**Comment by jean-gui** [comment]
I cannot reproduce this either. Let's wait for @koalie to check again.

**Comment by koalie** [comment]
I still have the same bug. But since I'm apparently the only one, I'll probably need to change browser to work on the CMS, as I have zero idea what setting to toggle in Mac OS Firefox to fix this.

**Comment by koalie** [comment]
Thank you @JamieC24 and @jean-gui

**Comment by koalie** [comment]
@JamieC24 and @jean-gui I was able to reproduce the bug:
In your Firefox settings, "General", "Font": I changed the default from size 16 to anything smaller. Reload. Re-try a picker, you'll see the picker's side-bar receding more and more outside of its box the smaller font size you choose.

**Comment by jean-gui** [comment]
I was able to reproduce on both Vivaldi and Firefox

**Comment by jean-gui** [comment]
@koalie opened an issue on Craft repo: https://github.com/craftcms/cms/issues/17809
